train_files:
- Fov1_DC
- Fov2_DC
- Fov3_DC
- Fov5_DC

test_files:
- Fov6_DC

model: LC1

channels: [0,0]

lr: 0.001

epochs: 50

nimg_per_epoch: 4

min_train_masks: 1

model_name: model.pt

save_every: 1

labels: ["egfr", "ereg"]