train_files:
- ereg_568_egfr_647_fov2
- ereg_647_egfr_568_fov2_dc
- ereg_568_egfr_647_fov4
- ereg_647_egfr_568_fov3_dc
- ereg_647_egfr_568_fov1_dc

test_files:
- ereg_568_egfr_647_fov2
- ereg_647_egfr_568_fov2_dc
- ereg_568_egfr_647_fov4
- ereg_647_egfr_568_fov3_dc
- ereg_647_egfr_568_fov1_dc
