labels: ["egfr", "ereg"]

# whether to sum channels (currently only channel 0 and 1)
sum_chan: True

img_interpolate: log2

img_threshold: 0

learning_rate: 0.01

weight_decay: 0.0001

epochs: 1

batch_size: 2

num_workers: 1

use_gpu: True

train_transforms:
  rotation: 90 # number of nm
  h_flip: null
  v_flip: null
  erasing: null
  perspective: 0.2
  dtypeconv: null

test_transforms:
  dtypeconv: null
